version: '3'

services:
  ticker-nginx:
    image: nginx:stable-alpine
    container_name: ticker-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    #      -  /mnt/data/certs:/etc/nginx/certs
    depends_on:
      - ticker-php
    networks:
      - tickernet

  ticker-mysql:
    image: mysql:5.7.29
    hostname: mysql_server
    container_name: ticker-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: ticker
      MYSQL_USER: ticker
      MYSQL_PASSWORD: ticker123
      MYSQL_ROOT_PASSWORD: ticker123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - tickernet
    volumes:
      - ./sqldata:/var/lib/mysql

  ticker-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticker-php
    volumes:
      - ./:/var/www/html/app
    ports:
      - "9000:9000"
    networks:
      - tickernet
  ticker-redis:
    image: redis:4.0
    container_name: ticker-redis
    ports:
      - "6382:6379"
    networks:
      - tickernet
networks:
  tickernet:
    external: true
